export const COURSES = [
  {
    id: 1,
    name: '法国歌剧史与欣赏',
    teacher: '孙仰辉',
    weeks: [2, 3, 4, 5, 6, 7, 8, 9],
    location: '教学一号楼 3004',
    day: 1,
    startPeriod: 1,
    endPeriod: 2,
  },
  {
    id: 2,
    name: '大学计算机基础',
    teacher: '张莹莹',
    weeks: [2, 3, 5, 6, 7, 8, 9],
    location: '计算机房(R1-4090)',
    day: 2,
    startPeriod: 3,
    endPeriod: 5,
  },
  {
    id: 3,
    name: '综合法语(1)',
    teacher: 'GUIHO MYLENE',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学二号楼',
    day: 3,
    startPeriod: 3,
    endPeriod: 4,
  },
  {
    id: 4,
    name: '体育(1)',
    teacher: '姚平',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '杭州田径场',
    day: 4,
    startPeriod: 1,
    endPeriod: 2,
  },
  {
    id: 5,
    name: '航空航天概论A',
    teacher: '田云',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学一号楼 2003',
    day: 4,
    startPeriod: 3,
    endPeriod: 4,
  },
  {
    id: 6,
    name: '习近平新时代中国特色社会主义思想',
    teacher: '董卓宁',
    weeks: [3],
    location: '科研一号楼 1040',
    day: 5,
    startPeriod: 1,
    endPeriod: 4,
  },
  {
    id: 7,
    name: '综合法语(1)',
    teacher: '徐梦琪',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学二号楼 4004',
    day: 1,
    startPeriod: 6,
    endPeriod: 7,
  },
  {
    id: 8,
    name: '综合法语(1)',
    teacher: '徐梦琪',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学二号楼 4004',
    day: 2,
    startPeriod: 6,
    endPeriod: 7,
  },
  {
    id: 9,
    name: '数学基础',
    teacher: '陈欢',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '科研一号楼 1001',
    day: 4,
    startPeriod: 6,
    endPeriod: 7,
  },
  {
    id: 10,
    name: '综合法语实训(1)',
    teacher: 'GUIHO MYLENE',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学二号楼',
    day: 1,
    startPeriod: 8,
    endPeriod: 9,
  },
  {
    id: 11,
    name: '心理健康(1)',
    teacher: '方瑶',
    weeks: [3],
    location: '教学一号楼 2004',
    day: 3,
    startPeriod: 8,
    endPeriod: 9,
  },
  {
    id: 12,
    name: '基础英语(1)',
    teacher: '王金森',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学一号楼 4005',
    day: 1,
    startPeriod: 11,
    endPeriod: 12,
  },
  {
    id: 13,
    name: '综合法语(1)',
    teacher: 'GUIHO MYLENE',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学二号楼',
    day: 4,
    startPeriod: 11,
    endPeriod: 12,
  },
  {
    id: 14,
    name: '综合法语实训(1)',
    teacher: 'GUIHO MYLENE',
    weeks: Array.from({ length: 16 }, (_, i) => i + 2),
    location: '教学二号楼',
    day: 5,
    startPeriod: 6,
    endPeriod: 7,
  },
];

export const CALENDAR = {
  fall2026Start: '2026-09-07',
  spring2027Start: '2027-03-01',
  totalWeeks: { fall: 19, spring: 18 },
};

export function getCurrentWeek() {
  const now = new Date();
  const start = new Date(CALENDAR.fall2026Start);
  const diff = Math.floor((now - start) / (1000 * 60 * 60 * 24));
  return Math.max(1, Math.floor(diff / 7) + 1);
}

export const DAY_NAMES = ['', '周一', '周二', '周三', '周四', '周五', '周六', '周日'];

export const TIME_SLOTS = [
  { period: 1, time: '08:00-08:45' },
  { period: 2, time: '08:50-09:35' },
  { period: 3, time: '09:50-10:35' },
  { period: 4, time: '10:40-11:25' },
  { period: 5, time: '11:30-12:15' },
  { period: 6, time: '14:00-14:45' },
  { period: 7, time: '14:50-15:35' },
  { period: 8, time: '15:50-16:35' },
  { period: 9, time: '16:40-17:25' },
  { period: 10, time: '17:30-18:15' },
  { period: 11, time: '19:00-19:45' },
  { period: 12, time: '19:50-20:35' },
  { period: 13, time: '20:40-21:25' },
  { period: 14, time: '21:30-22:15' },
];
